# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdd7b68d48c5ab6f47df593e3a0fe1f31dff6850e00fcd97dacaab8786f9713f857d6e7532362f7a144cb4fa15ddb94b46abda13a64f54431e30888932054129

test:
  secret_key_base: 508858b2779c95a0a6cf89c0c0e4ee2e245cb65f38b9a4e701a0b069a1dfd3c9a17d8d9051ea293a08903370476da940b54c4668b2ac9735984cb84ea3be8893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
